### PR TITLE
ENH: add roadmap

### PR DESCRIPTION
**Pull request by jasmainak**
cc @stephanie-r-jones 

see rendering: https://132-168215891-gh.circle-artifacts.com/0/html/roadmap.html

To build locally:

```sh
$ git clone git@github.com:jonescompneurolab/hnn-core.git
$ cd hnn-core
$ git remote add jasmainak git@github.com:jasmainak/hnn-core.git
$ git fetch jasmainak roadmap:roadmap
$ git checkout roadmap
```

then edit `roadmap.rst`. To see the rendered html, do:

```sh
$ cd doc/
$ make html-noplot
```

and open the `_build/html/roadmap.html` file in a web browser. Once happy with the edits, push them:

```py
$ git add roadmap.rst
$ git commit -m "Updates to the roadmap"
$ git push jasmainak roadmap
```

Hopefully all this works. Let me know if you get any errors

### CODE REVIEW

**Comment by jasmainak** [comment]
@blakecaldwell any clue why Travis fails?

**Comment by blakecaldwell** [comment]
> @blakecaldwell any clue why Travis fails?

Maybe something was updated in the NEURON packaging?

`nrnivmodl` fails with the following. Not sure when it started attempting to link those libraries.
```
 => LINKING library x86_64/libnrnmech.dylib Mod files: ar.mod ca.mod cad.mod cat.mod dipole.mod dipole_pp.mod hh2.mod kca.mod km.mod vecevent.mod
(cd .. ; g++ -O2 -DVERSION_INFO='7.8.1' -std=c++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -fPIC  -I /Users/travis/miniconda/envs/testenv/lib/python3.7/site-packages/neuron/.data/include -o x86_64/libnrnmech.dylib -Wl,-install_name,@rpath/libnrnmech.dylib \
	  x86_64/mod_func.o x86_64/ar.o x86_64/ca.o x86_64/cad.o x86_64/cat.o x86_64/dipole.o x86_64/dipole_pp.o x86_64/hh2.o x86_64/kca.o x86_64/km.o x86_64/vecevent.o -L/Users/travis/miniconda/envs/testenv/lib/python3.7/site-packages/neuron/.data/lib -lnrniv -Wl,-rpath,/Users/travis/miniconda/envs/testenv/lib/python3.7/site-packages/neuron/.data/lib    -lreadline /Applications/Xcode_11.5.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libcurses.tbd /Applications/Xcode_11.5.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libform.tbd)
clang: error: no such file or directory: '/Applications/Xcode_11.5.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libcurses.tbd'
clang: error: no such file or directory: '/Applications/Xcode_11.5.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libform.tbd'
make[1]: *** [x86_64/libnrnmech.dylib] Error 1
make: *** [modl] Error 2
```

**Comment by jasmainak** [comment]
I took the liberty to merge this myself in order to move forward quickly!

**Comment by jasmainak** [comment]
@ramcdougal or @pramodk, do you mind taking a [quick look at the issue](https://github.com/jonescompneurolab/hnn-core/pull/119#issuecomment-662759398)? You can see it in the [travis build here](https://travis-ci.org/github/jonescompneurolab/hnn-core/jobs/714150384#L625). Any clue how we should go about fixing it? It seems related to using the pip installer. We didn't have this issue before.

**Comment by pramodk** [comment]
Sure!

> clang: error: no such file or directory: '/Applications/Xcode_11.5.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libcurses.tbd'
clang: error: no such file or directory: '/Applications/Xcode_11.5.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libform.tbd'

This is one of the issue that got introduced in Mac OS wheel. I have fixed this in https://github.com/neuronsimulator/nrn/pull/670 and `neuron-nightly` wheel should be working correctly. I will push patched version to pypi.org soon.

**Comment by jasmainak** [comment]
perfect, thank you so much!!

**Comment by pramodk** [comment]
Python wheel is [updated](https://pypi.org/project/NEURON/7.8.1.1/) on pypi.org. Could you re-trigger the build and see if issue is resolved now?

**Comment by jasmainak** [comment]
wow that was fast. Thanks a lot @pramodk ! It works perfectly now :)

**Pull request merged**
