### PR TITLE
[MRG] Add layered histogram

### PR DESCRIPTION
**Pull request by chenghuzi**
As titled:

image

### CODE REVIEW

**Comment by jasmainak** [comment]
Should the color for prox and dist be different?

**Comment by chenghuzi** [comment]
> Should the color for prox and dist be different?

I’d like to, but we don’t have access to it unless the original ﻿`plot_spikes_hist` is changed.

**Comment by jasmainak** [comment]
is the idea to have the 3 x 1 layout only the first plot after simulation? Subsequent plots will plot the proximal and distal together? Or would it make sense to add extra plot types : input histogram (distal) and input histogram (proximal) ?

**Comment by chenghuzi** [comment]
> is the idea to have the 3 x 1 layout only the first plot after simulation? Subsequent plots will plot the proximal and distal together? Or would it make sense to add extra plot types : input histogram (distal) and input histogram (proximal) ?

That’s the default option. For other manually added figures, users can still select the 1:1:6 layout and add those histograms themselves. I don’t think we need to provide a “packed” solution for histograms in the plot type section, as it requires manipulation across multiple axes. The manipulation of axes (using the layout dropdown menu) and plots (using the plot type dropdown menu) are currently orthogonal. However, if we really want it, we could achieve it by dynamically disabling some plot types for certain layouts and add an extra layer of simulating two sequential plotting operations.

**Comment by ntolley** [comment]
Closing because the GUI code is dramatically different, but @dylansdaniels this would be good to reference

I think that the better solution will be to have these on the same plot (instead of divided into two panels), and just flip the y-axis depending on if proximal or distal drives are specified

**Comment by dylansdaniels** [comment]
Sounds good, thanks @ntolley !

**Pull request closed without merging**
