### PR TITLE
[MRG] TST add check-manifest to CI

### LINKED ISSUE #242: add check_manifest to CI
https://pypi.org/project/check-manifest/

in preparation for the release

### PR DESCRIPTION
**Pull request by jasmainak**
closes #242

### CODE REVIEW

**Comment by jasmainak** [comment]
I ended up doing minor cosmetic changes for now. I'm not exactly sure how compiled files using `nrnivmodl` should be handled. Inclined to go with a less-than-perfect solution for now until someone figures out a better way.

**Comment by jasmainak** [comment]
@cjayb since you were the last one to touch the `Makefile` perhaps you can take a look at this PR?

**Comment by cjayb** [comment]
Makes complete sense to me, shall I merge?

**Comment by jasmainak** [comment]
you haven't accepted the invite to be a collaborator on the repo!

**Comment by jasmainak** [comment]
feel free to merge once you accept the invite :)

**Comment by cjayb** [comment]
Oops... Accepted now! I guess we're doing "Rebase & merge"? I haven't seen many Squashes in the logs?

**Comment by cjayb** [comment]
Since this was a 1 commit merge, I just went ahead with Squash & merge to see the result.

@jasmainak let me know if something else is desirable going forward in larger PRs.

**Comment by jasmainak** [comment]
I usually do "rebase and merge" to give the contributors credit for the work they did in terms of green squares on github :) Only exception to this rule is if it really is a small PR and too many commits have been made going back and forth. We might consider moving to "squash and merge" in the future once the repo matures.

**Pull request merged**
