### PR TITLE
MAINT: add a Dockerfile

### PR DESCRIPTION
**Pull request by blakecaldwell**
This follows the general scheme from the HNN Dockerfile. It is most useful for running on HPC cluster systems.

X is required for plotting, which requires more setup if not used on Linux systems. The regular 'agg' backend will not work within a docker container, so 'TkAgg' is used with X forwarding.

### CODE REVIEW

**Comment by jasmainak** [comment]
if you use matplotlib agg4 backend, plotting does not work? how will the dockerfile help?

**Comment by blakecaldwell** [comment]
> if you use matplotlib agg4 backend, plotting does not work? 
Which one are you talking about?
```
ValueError: Key backend: Unrecognized backend string 'agg4': valid strings are ['GTK3Agg', 'GTK3Cairo', 'MacOSX', 'nbAgg', 'Qt4Agg', 'Qt4Cairo', 'Qt5Agg', 'Qt5Cairo', 'TkAgg', 'TkCairo', 'WebAgg', 'WX', 'WXAgg', 'WXCairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
```

This is the response with just 'agg':
```
/home/hnn_user/hnn-core/hnn_core/dipole.py:222: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
```
> how will the dockerfile help?
Clusters with shared filesystems are difficult setup python environments. The filesystem is over a network, so conda is very slow during peak hours. This lets users start immediately.

**Comment by jasmainak** [comment]
Yes sorry you should use `'agg'` backend if X forwarding doesn't work. And save the figures to png. I don't still understand how dockerfile could help solve that? We could add dockerfile anyway but it would need more instructions for installation.

**Comment by blakecaldwell** [comment]
Ah, I think the first sentence of this pull request is making it seem like the point of this had to do with graphics. The point is for cluster environments, especially for our users at Brown. Correcting.

X forwarding works... with TkAgg. The agg backend will never work in a docker container even if it's run locally with docker for Mac. TkAgg seems a reasonable substitute. BTW this isn't for general users. I plan on triggering a docker hub build automatically so users at Brown can start using this now.

**Comment by blakecaldwell** [comment]
This really just served a one-time use case. I'm going to close this

**Pull request closed without merging**
