### PR TITLE
[MRG] Fix circleci timeout problem

### PR DESCRIPTION
**Pull request by chenghuzi**
As titled.

### CODE REVIEW

**Comment by rythorpe** [comment]
Is this ready to merge @chenghuzi?

**Comment by chenghuzi** [comment]
> Is this ready to merge @chenghuzi?

yes

**Comment by rythorpe** [comment]
I'd approve the rebase and merge myself but it only gives me the option to auto-merge. Any idea why this is @jasmainak?

**Comment by jasmainak** [comment]
I guess it's because "Linkcheck" is marked as a required test to pass ... we could change which tests are required but I suggest just fixing the linkcheck by ignoring the relevant link so we stop worrying about CIs once and for all

**Comment by rythorpe** [comment]
> I guess it's because "Linkcheck" is marked as a required test to pass ... we could change which tests are required but I suggest just fixing the linkcheck by ignoring the relevant link so we stop worrying about CIs once and for all

Hmm, I don't recall encountering this before when the linkcheck broke. Maybe I just forgot though.

Huzi fixed the linkcheck in #596 and we're just waiting to merge this PR before merging the other.

**Comment by jasmainak** [comment]
okay I bypassed the branch protection rules for this PR

**Comment by jasmainak** [comment]
Thanks @chenghuzi !

**Pull request merged**
