### PR TITLE
[MRG] fix layers 5 and 2 swapped depth dimension

### LINKED ISSUE #351: L5 cells are ABOVE L2 cells
Yes, that happened... No idea when, but it explains _so_ much in #329 ...

Don't believe me? Me neither, but it's been staring at us all along:

ping @jasmainak @ntolley @rythorpe

### PR DESCRIPTION
**Pull request by cjayb**
Closes #351

### CODE REVIEW

**Comment by cjayb** [comment]
Hmm, digging a little deeper, what's this doing @rythorpe:

https://github.com/jonescompneurolab/hnn-core/blob/c65bc1e1ffa3438727e0bc699aea09aae869ec81/hnn_core/cell.py#L319 

So `net.pos_dict` contains coordinates such that apical=Z, and `Cell` flips Z and Y so that apical sections are along Y?

Man it's hard to keep track of all these flips splattered all over the place! I'm honestly uncertain which way our dendrite `section` s are pointing!

**Comment by jasmainak** [comment]
yeah, this is what I saying [here](https://github.com/jonescompneurolab/hnn-core/pull/314#discussion_r643091576) @rythorpe

**Comment by jasmainak** [comment]
Thanks @cjayb ! Feel free to add a `whats_new` entry for this in your LFP pull request.

**Comment by rythorpe** [comment]
Just getting caught up - good catch here @cjayb! Looks like @jasmainak is dismantling the tyranny of incongruent morphology orientation in his most recent PR!

**Pull request merged**
