### PR TITLE
More hoc craziness

### PR DESCRIPTION
**Pull request by jasmainak**
@rythorpe check this out. Even this simple change on master doesn't work for me. Does it work for you?

### CODE REVIEW

**Comment by rythorpe** [comment]
This gives me the same segmentation fault as earlier. Is that what you're getting?

**Comment by rythorpe** [comment]
I think the problem occurs when `Network` tries to call neuron's `pc.cell()` method

**Comment by jasmainak** [comment]
> Is that what you're getting?

I am actually getting `HocError` or `RuntimeError`

**Comment by rythorpe** [comment]
After https://github.com/jonescompneurolab/hnn-core/pull/109/commits/edfb3ddfaf88d245b894fea9d59e5d8323692838?

**Comment by jasmainak** [comment]
> After edfb3dd?

yeah segmentation fault it is

**Comment by jasmainak** [comment]
It beats me why should it be different if it's in a class method vs a function

**Comment by jasmainak** [comment]
maybe @blakecaldwell has an idea how to solve this crazy segmentation fault issue :) I remember he did some ninja magic with this.

**Comment by blakecaldwell** [comment]
Stange, indeed. Can you determine whether the problem is from 1) placing connect_to_target outside of ExtFeed or 2) code changes to connect_to_target? I'm thinking an import issue, which would relate to (1), but I don't see it off-hand.

**Comment by jasmainak** [comment]
@blakecaldwell you're right that if I keep the function exactly the same it works. See my commit 6aab952. From python perspective the code before and after the diff looks equivalent to me, but somehow hoc doesn't like it

**Comment by blakecaldwell** [comment]
Yikes. Hard to explain that one.

**Comment by rythorpe** [comment]
Could it be a namespace issue? This is a long shot, but I was reading in the neuron documentation that `h.Netcon()` objects are left accessible by the `h.Netcon().record()` method; however, by initializing the `h.Netcon()` object in a function and then passing the object to a new namespace (i.e., rather than leaving it in the `ExtFeed()` object's namespace), maybe accessibility to the hoc instance is lost (e.g., via corruption of a pointer?).

**Comment by blakecaldwell** [comment]
@rythorpe a namespace issue could be it... Outside of a class, it may not be possible to have multiple unique `h.VecStim()` instances because of a namespace collision in hoc.

**Comment by jasmainak** [comment]
I tried to wrap the function in a class, didn't work either :)

**Comment by jasmainak** [comment]
@samnemo any clue? This seems like it could be tied to the `VecStim` object and I'm not an expert in editing mod files.

**Comment by samnemo** [comment]
I haven't encountered this particular issue. I would mention the problem to Michael Hines or Robert McDougal (primary NEURON developers) and see what feedback they have for you.

**Comment by jasmainak** [comment]
okay thanks @blakecaldwell and @samnemo both!

@rythorpe I think the next logical step is to reproduce this problem in an isolated script (and the eventvec.mod file which seems to be adapted from a Neuron example anyway). Right now, there are too many interactions happening in the network class. 

Take a random numpy sequency that would be your `event_times` and then feed it to our `artificial_cell` function. Do the same with a class instead of a function. Hopefully one of them works and the other doesn't. Then we can have a more meaningful discussion with Michael hines or Robert.

**Comment by rythorpe** [comment]
I'll give it a shot, though I can't for the life of me figure out what is so magical about the `ExtFeed` class. I've tried multiple versions of an `artificial_cell` class that have the same functionality as the `ExtFeed().artificial_cell()` method. None of them work. It's like there is something different about the `ExtFeed` class that requires `h.VecStim()` and `h.NetCon()` objects to be initialized within `ExtFeed` in order for `pc.cell()` to access the `h.NetCon()` instance within the `Network()` class.

**Comment by jasmainak** [comment]
> I'll give it a shot, though I can't for the life of me figure out what is so magical about the ExtFeed class.

this is why I say that let's try to reproduce this problem outside of `hnn-core`. I am quite certain it's a question of scope somehow. I read up a bit and it seems the `VecStim` object is not very well designed and is probably missing a destructor (search NetStim and Neuron). This could affect how it behaves in different scopes. The segmentation fault is probably a memory access issue.

> requires h.VecStim() and h.NetCon() objects to be initialized within ExtFeed

it does require h.VecStim() inside ExtFeed but if you take h.NetCon out, it still works. I tried this, you can also replicate this by moving the connect_to_target outside the class and not changing anything else. Hence my suspicion that it's a question of h.VecStim.

> within ExtFeed in order for pc.cell() to access the h.NetCon() instance within the Network() class

Let's try to simulate this scenario outside of `hnn-core` to get the "essence" of the problem. Ideally one script and if not two scripts. Very minimal (less than 20 lines of code) -- one with a class, one without. Make a function where you import `ParallelContext` and a "fake" ExtFeed class which creates the netcon and another function outside of ExtFeed where you create the netcon

By the way, one other thing to try is to pass a copy of objects. Because python always passes things by reference, it might mess up how you think about things. You might be passing something to the function but it's still attached to the class because you didn't make a copy.

**Comment by rythorpe** [comment]
@jasmainak I was finally able to successfully separate creation of all nrn objects from the `ExtFeed` class without causing a segmentation fault to occur during a simulation. I have tried replicating the basic structure of attempts that did and didn't work in the attached zip file; however, I have thus-far been unsuccessful at replicating the bug. If you run `demos.py` in the uncompressed `nrn_netcon_feed_bug` folder, it should run through 3 different scenerios, all of which currently work fine. I'm worried that my demos do not capture the true complexity of the problem that exists in hnn-core. Any suggestions?
[nrn_netcon_feed_bug.zip](https://github.com/jonescompneurolab/hnn-core/files/4843868/nrn_netcon_feed_bug.zip)

**Comment by rythorpe** [comment]
I also found [this](https://www.neuron.yale.edu/phpBB/viewtopic.php?t=2147#p10276) blog post on the NEURON forum. We may want to just add a destructor to the `VecStim` class.

**Comment by jasmainak** [comment]
@rythorpe I do get a segmentation fault on some of the runs. I think we are pretty close!! It might be a question of the random seed or something

**Comment by rythorpe** [comment]
> @rythorpe I do get a segmentation fault on some of the runs. I think we are pretty close!! It might be a question of the random seed or something

Which ones do you get a segmentation fault on?

**Comment by jasmainak** [comment]
I didn't check closely. I just ran the script a few times and it segfaulted for some of the runs. It could also be the case that VecStim is not threadsafe which could explain why it randomly segfaults sometimes

**Comment by rythorpe** [comment]
@jasmainak My email isn't letting me send the zip file so here is an updated version of the demos per our previous discussion.
[nrn_netcon_feed_bug.zip](https://github.com/jonescompneurolab/hnn-core/files/4854140/nrn_netcon_feed_bug.zip)

**Comment by jasmainak** [comment]
closing this in favor of offline discussion on email

**Pull request closed without merging**
