### PR TITLE
[MRG] DOC: add template for reporting installation issues

### PR DESCRIPTION
**Pull request by jasmainak**
I see myself asking the same questions to people when they report their installation issues. We can iterate and refine this as we get more complaints ...

### CODE REVIEW

**Comment by rythorpe** [comment]
Is there a proper way to view the new template? The text looks good besides...

**Comment by rythorpe** [comment]
Is it ready to merge?

**Comment by jasmainak** [comment]
yep!

**Comment by rythorpe** [comment]
Thanks @jasmainak!

**Comment by jasmainak** [comment]
ughgh: https://github.com/jonescompneurolab/hnn-core/blob/master/.github/DISCUSSION_TEMPLATE/installation.yml ... will follow up

**Comment by jasmainak** [comment]
see: https://github.com/jonescompneurolab/hnn-core/commit/b833ca683bd59908988d0a1b4969183a7da31ce0

**Pull request merged**
