### PR TITLE
[MRG] DOC: support multiple versions

### LINKED ISSUE #277: documentation for different versions
We should archive the 0.1 and make CircleCI push directly to 0.2.dev0 and there should be a tab in the navbar for this

@sappelhoff can I solicit your help for this? I remember you did this for mne-bids! What do we need to do?

### PR DESCRIPTION
**Pull request by jasmainak**
closes #277

### CODE REVIEW

**Review by sappelhoff — APPROVED** [review]

**Comment by jasmainak** [comment]
Thanks @sappelhoff for the quick look. Okay I'm off for a walk, hope all hell doesn't break lose because of this change :)

**Comment by sappelhoff** [comment]
> hope all hell doesn't break lose because of this change :)

fingers crossed, but I'd be surprised if it *doesn't* need at least *some* iteration :wink:

**Comment by sappelhoff** [comment]
I just checked and it looks good --> only one thing: the v1 / stable version does not have the dropdown menu to select versions ... obviously because these were just added to dev.

I remember that for mne-bids I "backported" this docs feature to all old versions and rebuilt each of them, using the maint/XYZ branches. Was a lot of work, but for hnn-core there is only one version, so it would be quite easy I think.

**Comment by sappelhoff** [comment]
for practically experiencing my previous post, check also https://mne.tools/mne-bids/stable/index.html

being at the most recent "stable" version will allow you to see in the versions dropdown menu:

- all previous versions
- stable
- master

but nothing else.

Check it out by selecting v0.2 --> the dropdown menu for 0.2 only shows 0.1, stable, dev.

**Comment by jasmainak** [comment]
> I just checked and it looks good

the dropdown menu just shows "v". I fixed it in #280 now

**Pull request merged**
