### PR TITLE
Adding Google Analytics tag

### PR DESCRIPTION
**Pull request by dylansdaniels**
Adding Analytics tag to HEAD

### CODE REVIEW

**Comment by jasmainak** [comment]
Thanks a lot @dylansdaniels !

Do you want to add the email you used to make the commits to your github profile? It seems that it doesn't link to your profile

**Comment by dylansdaniels** [comment]
@jasmainak No problem!!! And hmmm, I wasn't logged in when I pushed those commits to my fork, so I think that's why they aren't linked to my profile. I'm not sure how to fix that retroactively, since I think GitHub views those commits as from a separate user without an account. (But if you know how to fix it, please let me know and I'll do so!)

It looks like the merge is still linked to my profile though - is it showing up that way for you? I think it should say something along the lines of "merge from @dylansdaniels with contributions from Dylan Daniels's MacBook Pro"

**Comment by jasmainak** [comment]
Did you make these commits from the web-UI? If you did them on your local computer, you should check if the email is set by doing:

```sh
git config --list
```

If it's not set, you need to do:

```sh
git config --global user.email [your email address here]
```

and then make sure that this email is added to your github profile by doing:

https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-email-preferences/adding-an-email-address-to-your-github-account

I just took a look and it seems you have this in your commit:

```sh
commit 27c63b8449a6a4fc11b18d9e73e0e7de831a77b3 (HEAD -> master, upstream/master)
Author: dylansdaniels <dylansdaniels@gmail.com>
Date:   Wed Jun 16 20:49:16 2021 -0700

    Adding Google Analytics tag (#362)
    
    * adding Analytics id to header
    
    * changed head to extrahead per Sphinx documentation
    
    * rename template to layout
    
    * move text
    
    * remove admin
    
    Co-authored-by: Dylan Daniels <dylandaniels@Dylans-MacBook-Pro-2.local>
```

which probably means you haven't set your email address in the git locally. You should do that in any case for future git commits. It can be retroactively fixed by updating the mailmap (or by doing a rebase before it was merged) but probably not worth the effort ...

**Comment by dylansdaniels** [comment]
@jasmainak it's working now for the new commit, just had to add my email locally  :-)

**Pull request merged**
