### PR TITLE
[MRG] DOC: add 'About' section to README.rst

### LINKED ISSUE #676: [JOSS] Documentation
Linking https://github.com/openjournals/joss-reviews/issues/5848 to track review progress.

Just one very minor change:

>  A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?

Maybe add a few sentences to https://jonescompneurolab.github.io/hnn-core/stable/index.html after "This is a leaner and cleaner version of the code based off the [HNN repository](https://github.com/jonescompneurolab/hnn)."?  Something like the **About** section in the [GitHub page](https://github.com/jonescompneurolab/hnn-core). Direct copy and paste works too.

### PR DESCRIPTION
**Pull request by rythorpe**
fixes #676

### CODE REVIEW

**Review by jasmainak — APPROVED** [review]
LGTM. Merge button is yours @ntolley !

**Comment by rythorpe** [comment]
We're now getting the same matplotlib error for the ubuntu build as with the windows build: `FAILED hnn_core/tests/test_viz.py::test_network_visualization - AttributeError: 'FigureCanvasAgg' object has no attribute 'button_press_event'`. Any idea how to fix this @jasmainak?

**Comment by jasmainak** [comment]
looks like they've changed their API slightly. See this example:

https://matplotlib.org/stable/gallery/event_handling/coords_demo.html

we need to update our test. If it's used outside of tests, we may need some `if`/`else` how MNE does it:

https://github.com/mne-tools/mne-python/blob/079c868240a898204bf82b2f1bf0e04cdee75da1/mne/viz/utils.py#L864

**Comment by rythorpe** [comment]
Hmm, this is looking a bit more involved than I was expecting. I'll need to orient myself with the GUI code more before proceeding - if anyone wants to give it a shot, go for it. Otherwise, I'll try to tackle it next week.

**Comment by rythorpe** [comment]
I moved all the other stuff about fixing the recent dependency breakage to #678 so that we can move forward with this PR despite the tests not passing.

Feel free to merge whenever you're ready @ntolley!

**Comment by ntolley** [comment]
Looks like I don't have the right permissions to merge! @jasmainak can you merge when the tests are failing? Or is this hard-coded in our security settings

**Comment by rythorpe** [comment]
Any update here @jasmainak?

**Comment by jasmainak** [comment]
I over-rode the failing test and merged. Thanks @rythorpe for the PR ! Let's try to fix the failing test as soon as we can

**Pull request merged**
