### PR TITLE
[MRG, DOC] Fix contributing install instructions

### PR DESCRIPTION
**Pull request by alexrockhill**
Addresses https://github.com/jonescompneurolab/hnn-core/issues/311.

### CODE REVIEW

**Comment by jasmainak** [comment]
Did you check that it works?

**Comment by alexrockhill** [comment]
> Did you check that it works?

Yes, it works :) Just checked right after you asked ;)

**Comment by jasmainak** [comment]
Groovy! Thanks for improving the contributing guide @alexrockhill

**Comment by cjayb** [comment]
Nice, thanks @alexrockhill !

**Pull request merged**
