### PR TITLE
[MRG] Remove connection probability inputs

### PR DESCRIPTION
**Pull request by chenghuzi**
As suggested by @jasmainak

### CODE REVIEW

**Comment by jasmainak** [comment]
The diff includes also the ERP tutorial ... can you do a smaller diff?

**Comment by ntolley** [comment]
Looks great! Just restarted the failed linkcheck, @chenghuzi @jasmainak ready to merge?

**Review by jasmainak — APPROVED** [review]

**Comment by jasmainak** [comment]
@chenghuzi set the PR to [MRG] when ready. It's good on my end. 

merge button is yours @ntolley !

**Comment by jasmainak** [comment]
I'll go ahead and merge to keep things moving. Thx @chenghuzi

**Pull request merged**
