### PR TITLE
MRG: Add TFR functions to externals

### PR DESCRIPTION
**Pull request by jasmainak**
This removes any dependency on MNE.

### CODE REVIEW

**Comment by jasmainak** [comment]
@cjayb please take a look. I think I'd prefer it this way. The rule is that anything in externals doesn't need to be tested because it's copied from the original repo (more or less in this case ...)

**Comment by cjayb** [comment]
Looks reasonable to me. There's a lot more in there than we actually need (for Morlet), partly due to mne supporting parallelisation over channels and/or epochs etc. But this is still a lot lighter-weight than a hard dependency on all of mne. I'm +1 for this, not least because I don't see the viz-module being something we'll put much effort in going forward. I think it's doing a few things pretty OK now; good enough for most aspiring users to get a feel of what they're simulating.

I added the missing `__init__.py`, my first direct push to someone else's branch! For the record, it required specifying the local branch name explicitly: `git push -u jasmainak pr/jasmainak/274:externals_tfr`

I'll merge when CI's go green.

**Review by cjayb — APPROVED** [review]
All good!

**Comment by jasmainak** [comment]
Thanks @cjayb ! Great teamwork

If your local branch has the same name as the remote branch, you can just do:

```sh
$ git push jasmainak externals_tfr
```

But whatever works, everyone uses git differently :)

**Pull request merged**
