### PR TITLE
[MRG] ENH: make alpha example clearer

### LINKED ISSUE #451: the alpha/beta example should show driving input histograms
It's a bit hard to interpret the simulation without this info

### PR DESCRIPTION
**Pull request by jasmainak**
closes #451

### CODE REVIEW

**Comment by rythorpe** [comment]
LGTM, minus the elusive sphinx-gallery issue. Any ideas?

**Comment by jasmainak** [comment]
No clue :( I need to investigate. Or ask help of an experienced `sphinx-gallery` expert ...

**Comment by jasmainak** [comment]
@larsoner do you have any idea why `sphinx-gallery` complains here? This is the error log:

https://circleci.com/api/v1.1/project/github/jonescompneurolab/hnn-core/2080/output/108/0?file=true&allocation-id=61b26e353ae6874938bfb6a1-0-build%2F6706B66E

I'm not too familiar with `sphinx-gallery` codebase to meaningfully understand the error message.

```py
Traceback (most recent call last):
  File "/home/circleci/miniconda/envs/testenv/lib/python3.6/site-packages/sphinx/events.py", line 101, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/circleci/miniconda/envs/testenv/lib/python3.6/site-packages/sphinx_gallery/docs_resolv.py", line 443, in embed_code_links
    _embed_code_links(app, gallery_conf, gallery_dir)
  File "/home/circleci/miniconda/envs/testenv/lib/python3.6/site-packages/sphinx_gallery/docs_resolv.py", line 354, in _embed_code_links
    cobj, full_fname, return_type=True)
  File "/home/circleci/miniconda/envs/testenv/lib/python3.6/site-packages/sphinx_gallery/docs_resolv.py", line 260, in resolve
    self._link_cache[full_name] = self._get_link_type(cobj)
  File "/home/circleci/miniconda/envs/testenv/lib/python3.6/site-packages/sphinx_gallery/docs_resolv.py", line 193, in _get_link_type
    match = self._searchindex['objects'][first][second]
TypeError: list indices must be integers or slices, not str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/circleci/miniconda/envs/testenv/lib/python3.6/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/circleci/miniconda/envs/testenv/lib/python3.6/site-packages/sphinx/application.py", line 381, in build
    self.events.emit('build-finished', None)
  File "/home/circleci/miniconda/envs/testenv/lib/python3.6/site-packages/sphinx/events.py", line 110, in emit
    (listener.handler, name), exc, modname=modname) from exc
sphinx.errors.ExtensionError: Handler <function embed_code_links at 0x7fa8ee1ecbf8> for event 'build-finished' threw an exception (exception: list indices must be integers or slices, not str)
```

**Comment by larsoner** [comment]
This should be fixed in the latest sphinx gallery release I think. If it's not, it should be fixed in latest master

**Comment by jasmainak** [comment]
Alright, `sphinx-gallery` master seems to fix it. Thanks @larsoner !

@rythorpe good to go on my end

**Review by rythorpe — APPROVED** [review]

**Comment by rythorpe** [comment]
Thanks @jasmainak!

**Pull request merged**
