### PR TITLE
[MAINT][WIP] Simulate dipole enh

### PR DESCRIPTION
**Pull request by jasmainak**
Just opening the PR with the intent of finishing it later

### CODE REVIEW

**Comment by jasmainak** [comment]
I could use a bit of help in this @rythorpe or #314

**Comment by rythorpe** [comment]
What's the goal of this PR besides to add `tstop` and `dt`?

While we're at it, wdyt of implementing the capability of a burn-in period?

**Comment by jasmainak** [comment]
Burn-in would be a bit more complicated I suppose? You'd need to make sure that downstream analysis pipelines are aware of what the burn-in is and adjust the plots accordingly

**Comment by jasmainak** [comment]
@rythorpe the goal is to get rid of code like this:

https://github.com/jonescompneurolab/hnn-core/blob/8c071863cbb249c8f83d6622b1cce9331842c9aa/examples/plot_simulate_mpi_backend.py#L38-L40

as much as possible

**Comment by jasmainak** [comment]
@cjayb would it be acceptable to you if we made `tstop` compulsory argument to `add_xxx_drives` ? Currently, we were secretly passing `tstop` to `Network` instead of `simulate_dipole` which seems a bit semantically wrong to me. I think we might be able to make it more intelligent down the line but it's too tangled for me right now to make any sense of things unless I make it compulsory

**Comment by cjayb** [comment]
> which seems a bit semantically wrong to me

Agreed! `tstop` is a parameter of the simulation, not the network. Poisson and bursty drives already take `tstop`, but the implementation there is still dependent on the idea that the end-time of a simulation is known at the time the `add_XXX`-method is called. I don't think this needs to be so. We can do validation/sanity checks on the drive parameters after `simulate` is called. I think `tstop=None` still makes sense as a good default for Poisson and bursty, no?

**Comment by jasmainak** [comment]
closed by #397

**Pull request closed without merging**
