### PR TITLE
[MRG] MAINT: fix linkcheck

### PR DESCRIPTION
**Pull request by rythorpe**

### CODE REVIEW

**Comment by rythorpe** [comment]
@jasmainak the linkcheck now gets past the import stage and runs for about ~1 min longer, but there's a new error that I'm not sure what do with. Will the process exit with an error even if sphinx-gallery only raised warnings?
```
Sphinx-Gallery gallery_conf["plot_gallery"] was False, so no examples were executed.
build finished with problems, 24 warnings.
make: *** [Makefile:56: linkcheck] Error 1
make: Leaving directory '/home/runner/work/hnn-core/hnn-core/doc'
Error: Process completed with exit code 2.
```

**Comment by jasmainak** [comment]
umm ... actually there is an error if you read the log carefully:

```sh
/home/runner/work/hnn-core/hnn-core/hnn_core/network.py:docstring of hnn_core.network.Network.add_electrode_array:19: ERROR: Undefined substitution referenced: "---x---".
```

**Comment by rythorpe** [comment]
> umm ... actually there is an error if you read the log carefully:
> 
> ```shell
> /home/runner/work/hnn-core/hnn-core/hnn_core/network.py:docstring of hnn_core.network.Network.add_electrode_array:19: ERROR: Undefined substitution referenced: "---x---".
> ```

Okay, I've figured out how to fix some of them but there's still an elusive indentation error that I can't figure out. Any ideas?

**Comment by rythorpe** [comment]
Nevermind, there it is!

**Comment by rythorpe** [comment]
Okay, I just played around with things a bit to determine the minimum number of changes to get the linkcheck to pass. Turns out 3 things were needed:

1. installing the base hnn-core dependencies prior to the linkcheck allows `sphinx-build` to successfully import the appropriate hnn-core modules
2. adding the base hnn-core directory to the `PATH` env variable
3. fixing a few discrepancies in the docstrings allowed sphinx-gallery to finish running through the rest of the linkcheck

**Comment by jasmainak** [comment]
Thanks @rythorpe for the fix !

**Pull request merged**
