### PR TITLE
Update GUI screenshot for readme

### PR DESCRIPTION
**Pull request by chenghuzi**

### CODE REVIEW

**Comment by jasmainak** [comment]
Thanks @chenghuzi !

**Comment by jasmainak** [comment]
don't we also have to add `ipympl` as an optional dependency?

**Comment by chenghuzi** [comment]
> don't we also have to add `ipympl` as an optional dependency?

I guess we already have that in `extras_require` in `setup.py`

**Comment by jasmainak** [comment]
I mean in the Readme where we specify the dependencies ...

**Pull request merged**
