### PR TITLE
[MRG] DOC: add JOSS badge and CITATION.cff

### PR DESCRIPTION
**Pull request by rythorpe**

### CODE REVIEW

**Comment by rythorpe** [comment]
@jasmainak do you think we need a citation statement in the README as well, or is the badge and "Cite this repository" tab Github adds with CITATION.cff adequate?

**Comment by jasmainak** [comment]
You won’t see the github tab on the website, so I think a redundancy in the
readme won’t hurt!

**Comment by rythorpe** [comment]
Here's how the citation section looks in the compiled README. If it looks good, feel free to merge @jasmainak.

image

**Comment by jasmainak** [comment]
Looks good, thanks @rythorpe !!

**Pull request merged**
