### PR TITLE
Support HNN legacy params

### PR DESCRIPTION
**Pull request by blakecaldwell**
This will work to read existing HNN parameter files without doing anything fancy to handle comments or invalid lines.

### CODE REVIEW

**Comment by blakecaldwell** [comment]
FYI @rythorpe if you want to use existing .param files once this is merged

**Comment by jasmainak** [comment]
I can merge this if it's good to go from your end!

**Comment by jasmainak** [comment]
For some reason, codecov didn't get triggered. Maybe it's related to the move to jonescompneurolab?

**Comment by blakecaldwell** [comment]
Oops

**Comment by blakecaldwell** [comment]
Okay, please merge. Thank you.

**Comment by jasmainak** [comment]
Thanks @blakecaldwell !

**Pull request merged**
