### PR TITLE
[MRG] MAINT: define dtype=object for ragged nested ndarrays in viz.py

### LINKED ISSUE #486: Matplotlib warning in plot_spikes_hist with multiple trials
With the following code:
```
#...
hnn_core_root = op.join(op.dirname(hnn_core.__file__))
params_fname = op.join(hnn_core_root, 'param', 'default.json')
params = read_params(params_fname)

# net = jones_2009_model()
net = Network(params, add_drives_from_params=True)

with MPIBackend():
    dpls = simulate_dipole(net, tstop=170., n_trials=3)

window_len, scaling_factor = 30, 3000
for dpl in dpls:
    dpl.smooth(window_len).scale(scaling_factor)

fig, axes = plt.subplots(2,
                         1,
                         sharex=True,
                         figsize=(6, 6),
                         constrained_layout=True)
plot_dipole(dpls, ax=axes[0], layer='agg', average=True)
net.cell_response.plot_spikes_hist(ax=axes[1])
#...
```

we got some warnings

image

We also got similar warnings for spike plots

### PR DESCRIPTION
**Pull request by rythorpe**
This is pretty straightforward and will hopefully reduce the number of warnings that get produced when building docs or running examples.

closes #486

### CODE REVIEW

**Comment by jasmainak** [comment]
any what's up with circleci?

**Comment by rythorpe** [comment]
> any idea what's up with circleci?

I just re-ran it and we're now getting the same CircleCI issue that's on master.

**Comment by rythorpe** [comment]
Also, I can't seem to figure out what's wrong with the linkcheck. I've double checked all the links that report as being broken but they work just fine for me.

**Comment by jasmainak** [comment]
we really need to fix this problem @chenghuzi ... the `gui/basic_gui_usage` example is too slow or not verbose

Merging this PR though

**Comment by jasmainak** [comment]
> I just re-ran it and we're now getting the same CircleCI issue that's on master.

but the error before was a different one ... are you sure it does not occur after the timeout error, hence you hid it by re-running circleci?

**Comment by jasmainak** [comment]
Thanks @rythorpe !

**Comment by rythorpe** [comment]
> > I just re-ran it and we're now getting the same CircleCI issue that's on master.
> 
> but the error before was a different one ... are you sure it does not occur after the timeout error, hence you hid it by re-running circleci?

That's a possibility actually - good question. I've never seen that error before though, and since this PR is so minimal, I think the chances are small.

**Comment by jasmainak** [comment]
I suspect the error was due to a new release of `sphinx-gallery` or `sphinx` ... let's fix it next time we see it

**Comment by chenghuzi** [comment]
> we really need to fix this problem @chenghuzi ... the `gui/basic_gui_usage` example is too slow or not verbose
> 
> Merging this PR though

sorry i've been pretty busy and didn't have time to look at this...

**Comment by chenghuzi** [comment]
> we really need to fix this problem @chenghuzi ... the `gui/basic_gui_usage` example is too slow or not verbose
> 
> Merging this PR though

I think we may need to find other ways to do this. Running all simulations in CI may not be the best practice

**Comment by jasmainak** [comment]
> Running all simulations in CI may not be the best practice

But we're not hitting the 1 hour timeout (yet) ... you have the wrong diagnosis. The problem is no output from the GUI example for too long

**Comment by chenghuzi** [comment]
> > Running all simulations in CI may not be the best practice
> 
> But we're not hitting the 1 hour timeout (yet) ... you have the wrong diagnosis. The problem is no output from the GUI example for too long

I'll check that again

**Comment by chenghuzi** [comment]
> > Running all simulations in CI may not be the best practice
> 
> But we're not hitting the 1 hour timeout (yet) ... you have the wrong diagnosis. The problem is no output from the GUI example for too long

I tried to execute the notebook directly on the CircleCI server via ssh and it takes less than 5 minutes to finish the conversion. That matches what I observed locally. I'm wondering what has caused the long running time in the CircleCI job. Even 30 minutes don't work as I tried to extend it.

**Comment by jasmainak** [comment]
That's strange. Is it because we are using Docker? What we use a VM. See: https://circleci.com/docs/using-linuxvm/ ? We have seen massive improvements in other repos by switching to a VM. Maybe worth trying?

**Comment by chenghuzi** [comment]
I'll check this

**Comment by chenghuzi** [comment]
Oh my... It takes less than 5 minutes to finish the building process! Here is my [first results](https://app.circleci.com/pipelines/github/chenghuzi/hnn-core/285/workflows/c9fc9e2f-8185-451b-89b3-932c147188ed/jobs/321). I need to verify it again

**Comment by chenghuzi** [comment]
Alright, that one is due to the existing cache. So I updated the cache key and tried again. The [latest one](https://app.circleci.com/pipelines/github/chenghuzi/hnn-core/286/workflows/f61d20b0-37d4-4293-b458-d1d23d9702c2/jobs/322) is still good enough, we should definitely move to linux vm!

**Comment by jasmainak** [comment]
great :) One other thing is to make your GUI example more verbose. This will prevent this issue from reoccuring if the GUI tutorial becomes longer. Is there a way to tell nbsphinx to print the outputs when building the documentation?

**Comment by chenghuzi** [comment]
> great :) One other thing is to make your GUI example more verbose. This will prevent this issue from reoccuring if the GUI tutorial becomes longer. Is there a way to tell nbsphinx to print the outputs when building the documentation?

The only way I can think of now is to disable something like `suppress_output` (I forgot the exact name). Or maybe there're some ways to redirect the kernel output to both the notebook frontend and sys.out. I need to do some research.

**Pull request merged**
