### PR TITLE
'type' changed to 'feed_type'

### PR DESCRIPTION
**Pull request by Kartik-Khandelwal**
### I had done my best, kindly tell me, if there any mistake?

### CODE REVIEW

**Comment by jasmainak** [comment]
Tests are failing, can you make them pass

**Comment by Kartik-Khandelwal** [comment]
> Tests are failing, can you make them pass

sir, what are my mistakes and how can i pass tests ?

**Comment by jasmainak** [comment]
we don't need you to do Ctrl + F and replace. I could have done that in 10 seconds. The idea of "good first issue" is to introduce the code to new contributors genuinely interested in contributing more complex contributions in the future. This would involve time spent in understanding the background material (reading HNN paper), contributing guide, and to understand the structure of the code. It might be too much for you.

I'm going to close the issue in a day or two if the diff does not improve by then.

**Comment by Kartik-Khandelwal** [comment]
Please don't close it at least for today....
I will again see and understand the code base...

**Comment by jasmainak** [comment]
closing in favor of #153

**Pull request closed without merging**
