### PR TITLE
[MRG] Reset File Upload Widget to Zero

### PR DESCRIPTION
**Pull request by kmilo9999**
added logic to reset the file uploaded widget value to zero after a file has been uploaded

### CODE REVIEW

**Comment by gtdang** [comment]
> @kmilo9999 is a good habit to use commit abbreviations:
> 
> image
> see: https://numpy.org/devdocs/dev/development_workflow.html

There are plugins for vscode and pycharm that help with this. I use the conventional commits one. 
https://www.conventionalcommits.org/en/v1.0.0/
https://marketplace.visualstudio.com/items?itemName=vivaxy.vscode-conventional-commits
https://plugins.jetbrains.com/plugin/13389-conventional-commit

Do you have any recommendations for tools that help you with commit standardization @jasmainak?

**Comment by kmilo9999** [comment]
> @kmilo9999 is a good habit to use commit abbreviations:
> 
> image
> see: https://numpy.org/devdocs/dev/development_workflow.html

Got it. I'll follow this standards on future commits

**Review by gtdang — APPROVED** [review]
Approved!

**Comment by jasmainak** [comment]
Thanks @kmilo9999 !! 🥳

**Comment by jasmainak** [comment]
> Do you have any recommendations for tools that help you with commit standardization @jasmainak?

not too strict about the commit messages ... but I try to adhere to standards and established norms in the Python scientific community when possible ... numpy, scipy, ipython, matplotlib, scikit-learn, nilearn, mne etc

**Pull request merged**
