### PR TITLE
[MRG] Add governance structure and update README

### PR DESCRIPTION
**Pull request by dylansdaniels**
Hi, I create a new governance structure .rst file and updated the README.rst to point to where the gh page will be hosted once published... I rendered the html files locally and they look good to me. I'm unclear on the process for posting the .html files generated...is there an Action that makes them automatically? is that a separate PR under the gh-pages branch? thx :)

### CODE REVIEW

**Comment by rythorpe** [comment]
This is great @dylansdaniels! I believe all .rst files within the doc directory get compiled and pushed to the `gh-pages` branch automatically by CircleCI.

Looks like linkcheck is failing but I think that's because its testing the link to the governance.html webpage which doesn't exist yet.

**Comment by jasmainak** [comment]
Perhaps add the html link in a follow up PR so we keep the CIs happy?

**Comment by samadpls** [comment]
Hi @dylansdaniels,
Following up on our meeting discussion, I wanted to suggest a small update to the README.md file. As we mentioned, updating the [#Roadmap](https://github.com/jonescompneurolab/hnn-core?tab=readme-ov-file#roadmap) link would be helpful for users.

**Comment by dylansdaniels** [comment]
@jasmainak sounds good, I can remove the http link for now :-)

@samadpls I think we landed on removing the roadmap entirely since it's out of date. I think it makes sense to lump that in with the f/u PR since that will be changing the README anyway?

**Comment by dylansdaniels** [comment]
Shall I change prefix to [MRG]?

**Comment by jasmainak** [comment]
Thanks @dylansdaniels !!

**Pull request merged**
